apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app-deployment
  namespace: rag-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-app
        image: your-dockerhub-username/rag-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-app-secret
              key: GOOGLE_API_KEY
