apiVersion: v1
kind: Service
metadata:
  name: rag-app-service
  namespace: rag-ns
spec:
  selector:
    app: rag-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer
