name: CI/CD to GKE

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Decode and save GCP credentials
        run: |
          echo "${{ secrets.GCP_KEY_BASE64 }}" | base64 -d > key.json

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project bold-network-442413-r6
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Install gke-gcloud-auth-plugin (via apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      - name: Build and Push Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/bold-network-442413-r6/rag-repo/rag-app:latest .
          docker push asia-south1-docker.pkg.dev/bold-network-442413-r6/rag-repo/rag-app:latest

      - name: Get GKE credentials and update deployment
        run: |
          gcloud container clusters get-credentials rag-cluster --region asia-south1
          kubectl set image deployment/rag-app-deployment rag-app=asia-south1-docker.pkg.dev/bold-network-442413-r6/rag-repo/rag-app:latest -n rag-ns
