name: Deploy to GKE

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: bold-network-442413-r6
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/bold-network-442413-r6/rag-repo/rag-app:latest .
 
      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/bold-network-442413-r6/rag-repo/rag-app:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials rag-cluster --region asia-south1
       
      - name: Apply Namespace
        run: kubectl apply -f namespace.yaml

      - name: Wait for namespace
        run: kubectl wait --for=condition=Established --timeout=60 namespace/rag-ns

      - name: Apply Deployment
        run: kubectl apply -f deployment.yaml

      - name: Apply Service
        run: kubectl apply -f service.yaml

      


      - name: Deploy to GKE
        run: |
          kubectl set image deployment/rag-app-deployment rag-app=asia-south1-docker.pkg.dev/bold-network-442413-r6/rag-repo/rag-app:latest -n rag-ns

     
